pipeline {
    agent any
 
    stages {
        stage('Hello') {
            steps {
                echo 'Hello'
            }
        }
         stage('Hi') {
            steps {
                echo 'How are you'
            }
        }
         stage('Bye') {
            steps {
                echo 'Thank you'
            }
        }
    }
}
